version: '3.8'

services:
  parsiktech:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parsiktech
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
